# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    # Allow all update types including major versions
    allow:
      - dependency-type: "all"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"